name: Build MineZero

on:
  push:
    branches: [ "1.21.1-fabric" ]
  pull_request:
    branches: [ "1.21.1-fabric" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12.1'

      - name: Build
        run: gradle build

      - name: Capture build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: MineZero-Artifacts
          path: build/libs/*.jar
          retention-days: 5
